Add code
viktoranddd/IU5-iOS-2022 pull request #1
Opened 2022-02-25 06:51 UTC by viktoranddd

## Товарищ, твой PR - твоя гордость!

- [ ] Убедись, что все тесты прошли успешно.
- [ ] Проверь, что Pull Request таргетоирован в ТВОЙ ФОРКНУТЫЙ main
- [ ] Заполни отчет по лабораторной работе в Google форме
- [ ] Улыбнись, ведь ты приобрел новые навыки)

## Важно!

После того, как ты заполнишь отчет по лабе, я или Юра поревьюим его, и напишем комментарии к коду, если будут вопросы.

Когда ты увидишь коментарий "Все ОК, мержи", можешь смержить PR.

- [ ] Ты увидел "Все ОК, мержи"?

2022-02-25 13:21 UTC, MrOcumare commented
Привет, а как ты создавал pull request?)

2022-02-25 13:58 UTC, viktoranddd commented
Сперва я по неопытности загрузил всё на GitHub в свою основную ветку и сделал Pull Request в ваш репозиторий. Понял, что это не хорошо, и закрыл его.
Потом я добавил у себя ветку lab1, где сделал все изменения, и создал Pull Request уже в свою master-ветку.

2022-02-27 09:02 UTC, MrOcumare requested changes
Молодец, шушучть поправь и максимальный бал в кармане

2022-02-27 09:02 UTC, MrOcumare commented on LABS/LAB_1/ArrayToString.swift
> +                }
лучше делать в формате
if <> {
} else {
}

2022-02-27 09:02 UTC, MrOcumare commented on LABS/LAB_1/ArrayToString.swift
> +        var string: String = ""
старайся давать переменным исчерпывающее значение
тут отлично подойдет что-то типо "resultString"

2022-02-27 09:02 UTC, MrOcumare commented on LABS/LAB_1/BooleanConverter.swift
> +        if string=="YES" {
if string == "YES" {

и не забудь про стиль } else {
смотри выше

2022-02-27 09:02 UTC, MrOcumare commented on LABS/LAB_1/SequenceСreator.swift
> +        var arr: [Int] = []
лучше resultArray

2022-02-27 09:02 UTC, MrOcumare commented on LABS/LAB_1/SequenceСreator.swift
> +        var arr: [Int] = []
лучше resultArray

2022-02-27 09:02 UTC, MrOcumare commented on LABS/LAB_1/SquareSum.swift
> +        var squareSum: Int = 0
вот тут четкое имя для переменной

2022-02-27 19:54 UTC, viktoranddd commented
Исправил замечания, но я не уверен, что правильно понял, как более корректно оформить конструкцию if-else (особенно в ArrayToString). Так что сообщите, если я всё ещё делаю нехорошо.

2022-02-28 19:54 UTC, MrOcumare commented
Все ОК, мержи

2022-02-28 19:55 UTC, MrOcumare commented
> Исправил замечания, но я не уверен, что правильно понял, как более корректно оформить конструкцию if-else (особенно в ArrayToString). Так что сообщите, если я всё ещё делаю нехорошо.

все правильно сделал)
Только внимательнее с отступами

2022-03-01 19:07 UTC, merged